/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module controlador_motor (
  input s1,
  input s2,
  output m1,
  output m2
);
  wire s0;
  wire s3;
  assign s0 = ~ s1;
  assign s3 = ~ s2;
  assign m1 = ((s0 & s3) | (s2 & s0));
  assign m2 = ((s0 & s3) | (s3 & s1));
endmodule
